services:
  frontend:
    image: burakcankorpinar/emine-yildirim-psikolog
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    container_name: emine-yildirim-psikolog
    hostname: emine-yildirim-psikolog
    environment:
      - DATABASE_URL=file:./prisma/dev.db
      - PORT=3000
    restart: always
    ports:
      - "5006:3000"
    volumes:
      # Veritabanını kalıcı hale getir (container restart edilince kaybetme)
      - ./prisma:/app/prisma
      # Public uploads klasörünü de kalıcı tut
      - ./public/uploads:/app/public/uploads